### ISSUE TITLE
CTP 6 Publish with Precompile option broken

### ISSUE THREAD

**Issue by bdelaney** [aspnet/vsweb-publish#12]
Has anyone tried this. I have been publishing without precompiling and using PS option. Today I wanted to take the plunge and see what a precompile might do. But nothing happened when I checked the box. So, I went into my build properties and ticked produce outputs on build. Then tried again. Nada. Same set of files in approot on Azure website. So, turn off the PS option. OMG, site fails to load. Approot, deployments, diagnostics, locks all gone from site. But wwwroot has nothing in bin but the loader file as always.
I'm doing a release config with default KRE, beta 3.

**Comment by sayedihashimi** [comment]
@vijayrkn thoughts?

**Comment by vijayrkn** [comment]
@bdelaney 
When you publish with "precompile option" selected, NuGet packages will be created for the project under approot/packates/<projectnam> folder. You will have to select "Delete existing files prior to publish" option along with "precompile option" because if you have both source and NuGet packages in the destination, runtime will always load from source first. Once both the options are checked and published, the site should work fine.

**Comment by sayedihashimi** [comment]
@bdelaney does that help you?

**Comment by sayedihashimi** [comment]
Closing since we haven't heard back from @bdelaney
