### ISSUE TITLE
reduce size of deploy package

### ISSUE THREAD

**Issue by markusvt** [aspnet/vsweb-publish#33]
I just deployed a quite small application and because of the dependencies, it resulted in an 60MB Upload to the Server.

Is it possible to reduce that size? I know every ASP.NET5 project is supposed to be self-sufficient, but maybe it is possible that instead of sending every dependend package from VS to the server, that just the project.json file with the dependencies is send and that the server afterwards loads those packages and stores them separately?
I'm just thinking about a webserver that hosts multiple websites that all depend on the same packages. Those websites could then share the central stored dependencies.

**Comment by sayedihashimi** [comment]
Hi @markusvt in order to support this we will need the ASP.NET 5/dnx runtime to support server side caching of packages/runtimes. This is something that we have discussed but have not implemented it yet. We are waiting for the runtime changes to settle down a bit before working on that. The correct repo for this feedback is the [dnx repo](https://github.com/aspnet/dnx) I believe. I think there may already be an existing issue tracking this but I'm not 100% sure. I know we are aware of it though.

I'm going to close this now, but after ASP.NET 5 has shipped this will be something that we will look to improve.
